Repository IvanBonk/FE-LAB-12-Team-Snow-Project, pull requests merged in 2020-04, with the labels that each got.

#42 Bugfix/page filter
  .eslintrc.js
  package.json
  src/App.tsx
  src/pages/Home.tsx
  src/pages/comparison/interfaces/filter.interface.ts
  src/pages/comparison/interfaces/pet.interface.ts
  src/pages/filter/components/button/button.component.tsx
  src/pages/filter/components/button/button.scss
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/pages/filter/components/filter-body/filter-body.scss
  src/pages/filter/components/filter-header/filter-header.component.tsx
  src/pages/filter/components/filter-header/filter-header.scss
  src/pages/filter/components/input-radio/input-radio.component.tsx
  src/pages/filter/components/input-switch/input-switch.component.tsx
  src/pages/filter/components/overview-checkboxes/overview-checkboxes.component.tsx
  src/pages/filter/components/petSize-checkboxes/petSize-checkboxes.component.tsx
  src/pages/filter/components/slider-section/slider-section.component.tsx
  src/pages/filter/components/slider/slider.component.tsx
  src/pages/filter/components/slider/slider.scss
  src/pages/filter/components/timePerMonth-checkboxes/timePerMonth-checkboxes.component.tsx
  src/pages/filter/filter.component.tsx
  src/pages/filter/filter.scss
  src/pages/search/components/modalBody.component.tsx
  src/pages/search/components/modalHeader.component.tsx
  src/pages/search/search.component.tsx
  src/pages/search/search.css
  src/pages/search/search.interfaces.tsx
  src/shared/constants/routes.constants.ts
  src/store/actions/filter.action.ts
  src/store/actions/search.action.ts
  src/store/filter.reducer.ts
  src/store/root.reducer.ts
  src/store/search.reducer.ts
  yarn.lock
Labels: bug

#43 bug-fix/Pet_Profile
  .eslintrc.js
  src/App.tsx
  src/components/pet/components/additional-item/additional.item.css
  src/components/pet/components/additional-item/additional.item.tsx
  src/components/pet/components/additional/additional.component.tsx
  src/components/pet/components/characteristics/characteristics.component.tsx
  src/components/pet/components/characteristics/characteristics.css
  src/components/pet/components/circles/circles.component.tsx
  src/components/pet/components/circles/circles.css
  src/components/pet/components/logo/logo.css
  src/components/pet/components/observations/observations.component.tsx
  src/components/pet/components/observations/observations.css
  src/components/pet/pet.component.tsx
  src/components/pet/pet.css
  src/pages/Pet.tsx
  src/pages/pet/components/additional-item/additional-item.component.tsx
  src/pages/pet/components/additional-item/additional-item.module.scss
  src/pages/pet/components/additional-item/arrow_down.svg
  src/pages/pet/components/additional-item/arrow_up.svg
  src/pages/pet/components/additionalInfo/additionalInfo.component.tsx
  src/pages/pet/components/back-btn/back-btn.component.tsx
  src/pages/pet/components/back-btn/back-btn.module.scss
  src/pages/pet/components/characteristics/characteristics.component.tsx
  src/pages/pet/components/characteristics/characteristics.module.scss
  src/pages/pet/components/logo/logo.component.tsx
  src/pages/pet/components/logo/logo.css
  src/pages/pet/components/logo/logo.svg
  src/pages/pet/components/logo/logo2.svg
  src/pages/pet/components/observations/observations.component.tsx
  src/pages/pet/components/observations/observations.module.scss
  src/pages/pet/components/rating/rating.component.tsx
  src/pages/pet/components/rating/rating.module.scss
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.models.ts
  src/pages/pet/pet.module.scss
  src/pages/pet/props.models.tsx
  src/shared/models.ts
  src/store/actions/pet.action.ts
  src/store/models.ts
  src/store/reducers/pet.reducer.ts
  src/store/reducers/search.reducer.ts
  src/store/root.reducer.ts
  src/store/root.saga.ts
  src/store/root.store.ts
  src/store/sagas/pet.saga.ts
Labels: bug

#44 Fix bugs in comparison page
  src/App.tsx
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/comparison.constants.ts
  src/pages/comparison/comparison.css
  src/pages/comparison/comparison.scss
  src/pages/comparison/components/characteristics.component.tsx
  src/pages/comparison/components/comparison-element.component.tsx
  src/pages/comparison/components/profile.component.tsx
  src/pages/comparison/components/rate-logic.service.tsx
  src/pages/comparison/components/rate.component.tsx
  src/pages/comparison/components/rate.css
  src/pages/comparison/components/rate.scss
  src/pages/comparison/interfaces/pet.interface.ts
  src/shared/constants/routes.constants.ts
  src/shared/interfaces/pet-profile.interface.ts
  src/shared/logotype/logo.tsx
  src/store/actions/comparison.action.ts
  src/store/models.ts
  src/store/reducers/comparison.reducer.ts
  src/store/root.reducer.ts
  src/store/root.saga.ts
  src/store/root.store.ts
  src/store/sagas/comparison.saga.ts
  src/store/services/get-pets-by-id-fetch.api.ts
  src/store/services/transform-data.comparison.ts
Labels: bug

#47 Create result page
  .eslintrc.js
  src/App.tsx
  src/pages/Result.tsx
  src/pages/pet/pet.component.tsx
  src/pages/result/components/dog-images/dog-images.component.tsx
  src/pages/result/components/dog-images/dog-images.styles.scss
  src/pages/result/components/dog-images/images/corgi1-small2.jpg
  src/pages/result/components/dog-images/images/corgi1.jpg
  src/pages/result/components/dog-images/images/corgi2-small2.jpg
  src/pages/result/components/dog-images/images/corgi2.jpg
  src/pages/result/components/dog-images/images/corgi3-small2.jpg
  src/pages/result/components/dog-images/images/corgi3.jpg
  src/pages/result/components/dog-search/dog-search.component.tsx
  src/pages/result/components/dog-search/dog-search.interfaces.ts
  src/pages/result/components/dog-search/dog-search.styles.scss
  src/pages/result/components/dog/dog.component.tsx
  src/pages/result/components/dog/dog.interfaces.ts
  src/pages/result/components/dog/dog.styles.scss
  src/pages/result/components/filter-button/filter-button.component.tsx
  src/pages/result/components/filter-button/filter-button.styles.scss
  src/pages/result/functions/filter.function.ts
  src/pages/result/result.component.tsx
  src/pages/result/result.interfaces.ts
  src/pages/result/result.styles.scss
  src/shared/conponents/dog-characteristic/dog-characteristic.component.tsx
  src/shared/conponents/dog-characteristic/dog-characteristic.styles.scss
  src/shared/conponents/dog-characteristic/dog-characteristics.interfaces.ts
  src/shared/interfaces.ts
  src/shared/logo/logo.component.tsx
  src/shared/logo/logo.image.svg
  src/shared/logo/logo.styles.css
  src/shared/logo/logo2.image.svg
  src/store/result/actions/result.actions.ts
  src/store/result/reducers/reducers.interfaces.ts
  src/store/result/reducers/result.reducer.ts
  src/store/result/sagas/result.saga.ts
  src/store/root.reducer.ts
  src/store/root.saga.ts
  src/store/root.store.ts
  src/store/sagas/pet.saga.ts
Labels: enhancement

#51 Bugfix/lint and routes
  .eslintrc.js
  src/App.tsx
  src/pages/Auth.tsx
  src/pages/Home.tsx
  src/pages/Registration.tsx
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/shared/constants/routes.constants.ts
  src/store/filter/actions/filter.action.ts
  src/store/filter/reducers/filter.reducer.ts
  src/store/root.reducer.ts
Labels: bug

#54 Bugfix/change-reducer-name
  src/pages/result/result.component.tsx
  src/pages/result/result.interfaces.ts
  src/store/result/reducers/result.reducer.ts
Labels: bug

#52 Bugfix/pet structure and store
  src/pages/User.tsx
  src/pages/comparison/components/rate-logic.service.tsx
  src/pages/comparison/components/rate.component.tsx
  src/pages/landing-page/components/find-out/find-out.component.tsx
  src/pages/landing-page/components/to-pick-up/to-pick-up.component.tsx
  src/pages/pet/components/additional-info/additional-info.component.tsx
  src/pages/pet/components/observations/observations.component.tsx
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.models.ts
  src/pages/pet/props.models.tsx
  src/shared/constants/routes.constants.ts
  src/shared/models.ts
  src/store/actions/pet.action.ts
  src/store/pet/actions/pet.actions.ts
  src/store/pet/pet.models.ts
  src/store/pet/reducers/pet.reducer.ts
  src/store/pet/sagas/pet.saga.ts
  src/store/reducers/pet.reducer.ts
  src/store/root.reducer.ts
  src/store/root.saga.ts
Labels: bug

#55 Add module styles and BEM methodology
  src/pages/result/components/dog-images/dog-images.component.tsx
  src/pages/result/components/dog-images/dog-images.module.scss
  src/pages/result/components/dog-images/dog-images.styles.scss
  src/pages/result/components/dog-search/dog-search.component.tsx
  src/pages/result/components/dog-search/dog-search.module.scss
  src/pages/result/components/dog-search/dog-search.styles.scss
  src/pages/result/components/dog/dog.component.tsx
  src/pages/result/components/dog/dog.module.scss
  src/pages/result/components/dog/dog.styles.scss
  src/pages/result/components/filter-button/filter-button.component.tsx
  src/pages/result/components/filter-button/filter-button.module.scss
  src/pages/result/components/filter-button/filter-button.styles.scss
  src/pages/result/result.component.tsx
  src/pages/result/result.module.scss
  src/shared/conponents/dog-characteristic/dog-characteristic.component.tsx
  src/shared/conponents/dog-characteristic/dog-characteristic.module.scss
  src/shared/conponents/dog-characteristic/dog-characteristic.styles.scss
Labels: bug

#58 Edit interfaces names where needed.
  src/pages/result/components/dog-images/dog-images.component.tsx
  src/pages/result/components/dog-search/dog-search.component.tsx
  src/pages/result/components/dog-search/dog-search.interfaces.ts
  src/pages/result/components/dog/dog.component.tsx
  src/pages/result/components/dog/dog.interfaces.ts
  src/shared/conponents/dog-characteristic/dog-characteristic.component.tsx
  src/shared/conponents/dog-characteristic/dog-characteristics.interfaces.ts
Labels: bug

#57 Modify Comparison page
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/comparison.interface.ts
  src/pages/comparison/comparison.scss
  src/pages/comparison/components/characteristics/characteristics.component.tsx
  src/pages/comparison/components/characteristics/characteristics.interface.ts
  src/pages/comparison/components/comparison-element/comparison-element.component.tsx
  src/pages/comparison/components/comparison-element/comparison-element.scss
  src/pages/comparison/components/profile/profile.component.tsx
  src/pages/comparison/components/profile/profile.interface.ts
  src/pages/comparison/components/profile/profile.scss
  src/pages/comparison/components/rate/rate-logic.service.tsx
  src/pages/comparison/components/rate/rate.component.tsx
  src/pages/comparison/components/rate/rate.interface.ts
  src/pages/comparison/components/rate/rate.scss
  src/shared/logotype/logo.css
  src/shared/logotype/logo.svg
  src/shared/logotype/logo.tsx
  src/shared/logotype/logo2.svg
  src/store/comparison/actions/comparison.action.ts
  src/store/comparison/reducers/comparison.reducer.ts
  src/store/comparison/sagas/comparison.saga.ts
  src/store/comparison/services/get-pets-by-id-fetch.api.ts
  src/store/comparison/services/transform-data.comparison.ts
  src/store/root.reducer.ts
  src/store/root.saga.ts
Labels: bug

#60 Change types notation
  src/pages/result/components/dog-search/dog-search.interfaces.ts
  src/pages/result/functions/filter.function.ts
  src/pages/result/result.interfaces.ts
  src/store/result/reducers/reducers.interfaces.ts
  src/store/result/reducers/result.reducer.ts
Labels: bug

#77 Modify Comparison page
  src/App.tsx
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/comparison.interface.ts
  src/pages/comparison/comparison.module.scss
  src/pages/comparison/comparison.scss
  src/pages/comparison/components/add-pet-button/add-pet-btn.module.scss
  src/pages/comparison/components/add-pet-button/add-pet-button.component.tsx
  src/pages/comparison/components/characteristics/characteristics.component.tsx
  src/pages/comparison/components/characteristics/characteristics.module.scss
  src/pages/comparison/components/comparison-display/comparison-display.component.tsx
  src/pages/comparison/components/comparison-display/comparison-display.interface.ts
  src/pages/comparison/components/comparison-display/comparison-display.module.scss
  src/pages/comparison/components/comparison-element/comparison-element.component.tsx
  src/pages/comparison/components/comparison-element/comparison-element.module.scss
  src/pages/comparison/components/empty/empty.component.tsx
  src/pages/comparison/components/empty/empty.module.scss
  src/pages/comparison/components/profile/profile.component.tsx
  src/pages/comparison/components/profile/profile.module.scss
  src/pages/comparison/components/rate/rate-logic.service.tsx
  src/pages/comparison/components/rate/rate.component.tsx
  src/pages/comparison/components/rate/rate.interface.ts
  src/pages/comparison/components/rate/rate.scss
  src/pages/comparison/components/remove-pet-button/remove-pet-button.component.tsx
  src/pages/comparison/components/remove-pet-button/remove-pet-button.interface.ts
  src/pages/comparison/components/remove-pet-button/remove-pet-button.module.scss
  src/pages/result/components/dog/dog.component.tsx
  src/shared/components/dog-characteristic/dog-characteristic.component.tsx
  src/shared/components/dog-characteristic/dog-characteristic.module.scss
  src/shared/components/dog-characteristic/dog-characteristics.interfaces.ts
  src/shared/components/rating/rating.component.tsx
  src/shared/components/rating/rating.interface.ts
  src/shared/components/rating/rating.module.scss
  src/shared/constants/routes.constants.ts
  src/store/comparison/actions/comparison.action.ts
  src/store/comparison/reducers/comparison.reducer.ts
  src/store/comparison/services/get-pets-by-id-fetch.api.ts
  src/store/comparison/services/transform-data.comparison.ts
Labels: enhancement

#81 Feature/care result page
  src/App.tsx
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/pages/filter/components/input-radio/input-radio.module.scss
  src/pages/petCare/components/additional-item/additional.interface.ts
  src/pages/petCare/components/additional-item/additonal-item.component.tsx
  src/pages/petCare/components/additional-item/additonal-item.module.scss
  src/pages/petCare/components/additional-item/arrow.svg
  src/pages/petCare/components/additional-item/up-arrow.svg
  src/pages/petCare/components/additonal-section/additional-section.component.tsx
  src/pages/petCare/components/additonal-section/additional-section.module.scss
  src/pages/petCare/components/analysis-item/analysis-item.component.tsx
  src/pages/petCare/components/analysis-item/analysis-item.module.scss
  src/pages/petCare/components/analysis-result/analysis-result.component.tsx
  src/pages/petCare/components/analysis-result/analysis-result.module.scss
  src/pages/petCare/components/analysis-result/result.interface.ts
  src/pages/petCare/components/analysis-section/analysis-section.component.tsx
  src/pages/petCare/components/analysis-section/analysis-section.module.scss
  src/pages/petCare/components/body-header/body-header.component.tsx
  src/pages/petCare/components/body-header/body-header.module.scss
  src/pages/petCare/components/care-body/care-body.component.tsx
  src/pages/petCare/components/care-body/care-body.module.scss
  src/pages/petCare/components/care-body/careBody.interface.ts
  src/pages/petCare/components/header.component/logo.svg
  src/pages/petCare/components/header.component/logo2.svg
  src/pages/petCare/components/header.component/petCare-header.component.tsx
  src/pages/petCare/components/header.component/petCare-header.module.scss
  src/pages/petCare/pet-care.component.tsx
  src/pages/petCare/pet-care.module.scss
  src/shared/constants/routes.constants.ts
  src/store/care/actions/care.actions.ts
  src/store/care/reducers/care.reducers.ts
  src/store/care/reducers/reducers.interfaces.ts
  src/store/care/sagas/care.sagas.ts
  src/store/root.reducer.ts
  src/store/root.saga.ts
Labels: enhancement

#80 Modify Comparison-page logic
  src/pages/comparison/comparison.interface.ts
  src/pages/comparison/components/remove-pet-button/remove-pet-button.component.tsx
  src/pages/pet/pet.component.tsx
  src/pages/result/result.component.tsx
  src/shared/components/add-pet-to-compare/add-pet-to-compare.component.tsx
  src/shared/components/add-pet-to-compare/add-pet-to-compare.interface.ts
  src/shared/components/add-pet-to-compare/add-pet-to-compare.module.scss
  src/shared/interfaces.ts
  src/shared/interfaces/pet-profile.interface.ts
  src/shared/models.ts
  src/store/comparison/actions/comparison-handler.action.ts
  src/store/comparison/reducers/comparison-handler.reducer.ts
  src/store/comparison/services/remove-pet-to-compare.ts
  src/store/root.reducer.ts
Labels: enhancement

#83 Apply filter
  src/pages/result/components/dog-search/dog-search.module.scss
  src/pages/result/components/dog/dog.module.scss
  src/pages/result/result.component.tsx
  src/pages/result/result.interfaces.ts
  src/pages/result/result.module.scss
  src/pages/result/utils/filter.util.ts
  src/shared/components/dog-characteristic/dog-characteristic.module.scss
  src/store/result/actions/result.actions.ts
  src/store/result/reducers/reducers.interfaces.ts
  src/store/result/reducers/result.reducer.ts
Labels: enhancement

#82 Alias support
  src/App.tsx
  src/index.tsx
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/components/add-pet-button/add-pet-button.component.tsx
  src/pages/comparison/components/comparison-element/comparison-element.component.tsx
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/pages/filter/components/filter-header/filter-header.component.tsx
  src/pages/landing-page/components/find-out/find-out.component.tsx
  src/pages/landing-page/components/to-pick-up/to-pick-up.component.tsx
  src/pages/landing-page/landing-page.component.tsx
  src/pages/pet/components/back-btn/back-btn.component.tsx
  src/pages/pet/pet.component.tsx
  src/pages/pet/props.models.tsx
  src/pages/result/components/dog-search/dog-search.interfaces.ts
  src/pages/result/components/dog/dog.component.tsx
  src/pages/result/components/dog/dog.interfaces.ts
  src/pages/result/components/filter-button/filter-button.component.tsx
  src/pages/result/result.component.tsx
  src/pages/result/result.interfaces.ts
  src/pages/result/utils/filter.util.ts
  src/store/comparison/actions/comparison.action.ts
  src/store/comparison/reducers/comparison.reducer.ts
  src/store/comparison/services/transform-data.comparison.ts
  src/store/filter/actions/filter.action.ts
  src/store/filter/reducers/filter.reducer.ts
  src/store/pet/actions/pet.actions.ts
  src/store/pet/pet.models.ts
  src/store/pet/reducers/pet.reducer.ts
  src/store/result/actions/result.actions.ts
  src/store/result/reducers/reducers.interfaces.ts
  tsconfig.json
Labels: enhancement

#84 Change img url path
  src/pages/filter/components/filter-header/filter-header.component.tsx
  src/pages/filter/components/filter-header/filter-header.module.scss
  src/pages/petCare/components/additional-item/additional.interface.ts
  src/pages/petCare/components/additional-item/additonal-item.component.tsx
  src/pages/petCare/components/additional-item/additonal-item.module.scss
  src/pages/petCare/components/additonal-section/additional-section.component.tsx
  src/pages/petCare/components/analysis-item/analysis-item.module.scss
  src/pages/petCare/components/body-header/body-header.component.tsx
  src/pages/petCare/components/care-body/care-body.component.tsx
  src/pages/petCare/components/care-body/careBody.interface.ts
  src/shared/constants/api.ts
  src/shared/constants/routes.constants.ts
  src/store/care/sagas/care.sagas.ts
Labels: enhancement

#88 change comparison logic in are page, change max val range in filter page
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/pages/filter/components/filter-header/filter-header.component.tsx
  src/pages/filter/components/filter-header/filter-header.module.scss
  src/pages/filter/components/petSize-checkboxes/petSize-checkboxes.component.tsx
  src/pages/filter/components/timePerMonth-checkboxes/timePerMonth-checkboxes.component.tsx
  src/pages/petCare/components/analysis-item/analysis-item.component.tsx
  src/pages/petCare/components/care-body/careBody.interface.ts
Labels: enhancement

#90 Modify filter
  src/App.tsx
  src/pages/result/components/dog-images/dog-images.component.tsx
  src/pages/result/components/dog-images/dog-images.interfaces.ts
  src/pages/result/components/dog-images/images/corgi1-small2.jpg
  src/pages/result/components/dog-images/images/corgi1.jpg
  src/pages/result/components/dog-images/images/corgi2-small2.jpg
  src/pages/result/components/dog-images/images/corgi2.jpg
  src/pages/result/components/dog-images/images/corgi3-small2.jpg
  src/pages/result/components/dog-images/images/corgi3.jpg
  src/pages/result/components/dog/dog.component.tsx
  src/pages/result/components/dog/dog.interfaces.ts
  src/pages/result/result.component.tsx
  src/pages/result/result.interfaces.ts
  src/pages/result/utils/filter.util.ts
  src/shared/interfaces.ts
Labels: enhancement

#89 Bugfix/pet page wasn't updating
  src/pages/pet/pet.component.tsx
  src/store/pet/sagas/pet.saga.ts
Labels: bug

#92 Release 1.3.0 to develop
  package.json
Labels: enhancement

#111 saving filter, remove requare, and button any, change colors
  src/pages/filter/components/button/button.module.scss
  src/pages/filter/components/filter-body/bodyFilter.intarface.ts
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/pages/filter/components/filter-body/filter-body.module.scss
  src/pages/filter/components/filter-header/filter-header.component.tsx
  src/pages/filter/components/input-radio/input-radio.component.tsx
  src/pages/filter/components/input-radio/input-radio.module.scss
  src/pages/filter/components/input-switch/input-switch.component.tsx
  src/pages/filter/components/input-switch/input-switch.module.scss
  src/pages/filter/components/overview-checkboxes/overview-checkboxes.component.tsx
  src/pages/filter/components/petSize-checkboxes/petSize-checkboxes.component.tsx
  src/pages/filter/components/slider-section/slider-section.component.tsx
  src/pages/filter/components/slider-section/slider-section.module.scss
  src/pages/filter/components/slider/slider.component.tsx
  src/pages/filter/components/slider/slider.module.scss
  src/pages/filter/components/timePerMonth-checkboxes/timePerMonth-checkboxes.component.tsx
  src/pages/filter/filter.interface.ts
  src/pages/filter/filter.scss
  src/store/filter/reducers/filter.reducer.ts
Labels: enhancement

#112 Add material icons & favicon
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/images/Logo/logo.image.svg
  src/images/Logo/logo2.image.svg
  src/pages/comparison/components/remove-pet-button/remove-pet-button.component.tsx
  src/pages/comparison/components/remove-pet-button/remove-pet-button.module.scss
  src/pages/pet/components/additional-item/additional-item.component.tsx
  src/pages/pet/components/additional-item/additional-item.module.scss
  src/pages/pet/components/additional-item/arrow_down.svg
  src/pages/pet/components/additional-item/arrow_up.svg
  src/pages/pet/components/logo/logo.component.tsx
  src/pages/pet/components/logo/logo.css
  src/pages/pet/components/logo/logo.svg
  src/pages/pet/components/logo/logo2.svg
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.module.scss
  src/shared/components/add-pet-to-compare/add-pet-to-compare.component.tsx
  src/shared/components/add-pet-to-compare/add-pet-to-compare.module.scss
  src/shared/logo/logo.component.tsx
  src/shared/logo/logo.styles.css
Labels: enhancement

#119 Modify root.store file
  .eslintrc.js
  src/pages/comparison/components/empty/empty.component.tsx
  src/pages/comparison/components/remove-pet-button/remove-pet-button.component.tsx
  src/pages/pet/pet.component.tsx
  src/shared/components/add-pet-to-compare/add-pet-to-compare.component.tsx
  src/store/comparison/actions/comparison-handler.action.ts
  src/store/comparison/reducers/comparison-handler.reducer.ts
  src/store/comparison/services/remove-pet-to-compare.ts
  src/store/result/reducers/reducers.interfaces.ts
  src/store/root.store.ts
Labels: enhancement

#120 Feature/comparison modify
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/comparison.constants.ts
  src/pages/comparison/comparison.module.scss
  src/pages/comparison/components/comparison-display/comparison-display.component.tsx
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.module.scss
  src/pages/result/result.component.tsx
  src/pages/result/result.module.scss
  src/shared/components/add-pet-to-compare/add-pet-to-compare.component.tsx
  src/shared/components/add-pet-to-compare/add-pet-to-compare.module.scss
  src/store/comparison/actions/comparison.action.ts
  src/store/comparison/reducers/comparison.reducer.ts
Labels: enhancement

#121 Add starter-pack component
  src/App.tsx
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.module.scss
  src/pages/pet/props.models.tsx
  src/pages/starter-pack/starter-pack.component.tsx
  src/pages/starter-pack/starter-pack.interfaces.ts
  src/pages/starter-pack/starter-pack.module.scss
  src/shared/constants/routes.constants.ts
  src/store/pet/actions/pet.actions.ts
  src/store/pet/sagas/pet.saga.ts
Labels: enhancement

#126 PetCare - padding, aliases, icons, router
  src/App.tsx
  src/pages/petCare/components/additional-item/additonal-item.component.tsx
  src/pages/petCare/components/additional-item/additonal-item.module.scss
  src/pages/petCare/components/additional-item/arrow.svg
  src/pages/petCare/components/additional-item/up-arrow.svg
  src/pages/petCare/components/additonal-section/additional-section.module.scss
  src/pages/petCare/components/analysis-result/analysis-result.module.scss
  src/pages/petCare/components/analysis-section/analysis-section.module.scss
  src/pages/petCare/components/body-header/body-header.module.scss
  src/pages/petCare/components/care-body/care-body.component.tsx
  src/pages/petCare/pet-care.module.scss
  src/shared/constants/routes.constants.ts
Labels: enhancement

#123 Filter page, min value.
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/pages/filter/components/slider-section/slider-section.component.tsx
  src/pages/filter/components/slider/slider.component.tsx
  src/pages/filter/filter.interface.ts
  src/store/filter/reducers/filter.reducer.ts
Labels: enhancement

#124 Add 'remove pet from comparison' button
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/components/remove-pet-button/remove-pet-button.component.tsx
  src/pages/pet/components/additional-item/additional-item.component.tsx
  src/pages/pet/pet.component.tsx
  src/pages/result/result.component.tsx
  src/shared/components/add-pet-to-compare/add-pet-to-compare.component.tsx
  src/shared/components/add-pet-to-compare/add-pet-to-compare.module.scss
  src/shared/components/loading-spinner/loading-spinner.module.scss
  src/shared/components/loading-spinner/loading-spinner.tsx
  src/shared/logo/logo.component.tsx
Labels: enhancement

#127 Enable user to go to the pet page from result page
  src/pages/result/components/dog/dog.component.tsx
  src/pages/result/components/dog/dog.interfaces.ts
  src/pages/result/result.component.tsx
Labels: enhancement

#128 Feature/filter data through url
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/store/filter/reducers/filter.reducer.ts
Labels: enhancement

#129 Feature/pet name generator
  src/App.tsx
  src/pages/pet/pet.component.tsx
  src/pages/starter-pack/components/name-generator/name-generator.component.tsx
  src/pages/starter-pack/components/name-generator/name-generator.interfaces.ts
  src/pages/starter-pack/components/name-generator/name-generator.module.scss
  src/pages/starter-pack/starter-pack.component.tsx
  src/pages/starter-pack/starter-pack.interfaces.ts
  src/pages/starter-pack/starter-pack.module.scss
  src/store/name-generator/actions/name-generator.actions.ts
  src/store/name-generator/name-generator.models.ts
  src/store/name-generator/reducers/name-generator.reducers.ts
  src/store/name-generator/sagas/name-generator.sagas.ts
  src/store/pet/actions/pet.actions.ts
  src/store/root.reducer.ts
  src/store/root.saga.ts
Labels: enhancement

#131 Create Pet Starter Pack Info Component
  src/pages/starter-pack/components/additional-info/additional-info.component.tsx
  src/pages/starter-pack/components/additional-info/additional-info.module.scss
  src/pages/starter-pack/components/back-btn/back-btn.component.tsx
  src/pages/starter-pack/components/back-btn/back-btn.interface.ts
  src/pages/starter-pack/components/back-btn/back-btn.module.scss
  src/pages/starter-pack/components/from-breeder/from-breeder.component.tsx
  src/pages/starter-pack/components/from-breeder/from-breeder.module.scss
  src/pages/starter-pack/components/to-buy/to-buy.component.tsx
  src/pages/starter-pack/components/to-buy/to-buy.interface.ts
  src/pages/starter-pack/components/to-buy/to-buy.module.scss
  src/pages/starter-pack/starter-pack.component.tsx
  src/pages/starter-pack/starter-pack.module.scss
Labels: enhancement

#132 Care page comparison logic
  src/pages/petCare/components/additional-item/additional.interface 2.ts
  src/pages/petCare/components/additional-item/additonal-item.module 2.scss
  src/pages/petCare/components/additonal-section/additional-section.component 2.tsx
  src/pages/petCare/components/additonal-section/additional-section.module 2.scss
  src/pages/petCare/components/analysis-item/analysis-item.component 2.tsx
  src/pages/petCare/components/analysis-item/analysis-item.component.tsx
  src/pages/petCare/components/analysis-item/analysis-item.interface.ts
  src/pages/petCare/components/analysis-item/analysis-item.module 2.scss
  src/pages/petCare/components/analysis-result/analysis-result.component 2.tsx
  src/pages/petCare/components/analysis-result/analysis-result.component.tsx
  src/pages/petCare/components/analysis-result/analysis-result.module 2.scss
  src/pages/petCare/components/analysis-result/result.interface 2.ts
  src/pages/petCare/components/analysis-section/analysis-section.module 2.scss
  src/pages/petCare/components/body-header/body-header.component 2.tsx
  src/pages/petCare/components/body-header/body-header.module 2.scss
  src/pages/petCare/components/care-body/care-body.component 2.tsx
  src/pages/petCare/components/care-body/care-body.component.tsx
  src/pages/petCare/components/care-body/care-body.module 2.scss
  src/pages/petCare/components/care-body/careBody.interface 2.ts
  src/pages/quiz-page/quiz-page.component.tsx
  src/store/care/actions/care.actions 2.ts
  src/store/care/reducers/care.reducers 2.ts
  src/store/care/reducers/reducers.interfaces 2.ts
Labels: enhancement

#133 Care page, change paddings, title, additional info
  src/pages/petCare/components/additonal-section/additional-section.component.tsx
  src/pages/petCare/components/analysis-item/analysis-item.component.tsx
  src/pages/petCare/components/analysis-result/analysis-result.component.tsx
Labels: bug

#135 Save filtred pets after reload the page
  src/pages/result/result.component.tsx
  src/pages/result/utils/getUrlValues.util.ts
  src/shared/constants/routes.constants.ts
Labels: enhancement

#136 Modify landing page
  src/pages/landing-page/components/find-out/find-out.component.tsx
  src/pages/landing-page/components/find-out/find-out.module.scss
  src/pages/landing-page/components/to-pick-up/to-pick-up.module.scss
  src/pages/landing-page/landing-page.component.tsx
  src/pages/landing-page/landing-page.module.scss
Labels: enhancement

#137 Show number of applied filters
  src/pages/result/components/filter-button/filter-button.component.tsx
  src/pages/result/components/filter-button/filter-button.interfaces.ts
  src/pages/result/result.component.tsx
  src/pages/result/result.interfaces.ts
  src/pages/result/utils/numberOfFilters.util.ts
  src/shared/constants/routes.constants.ts
Labels: enhancement

#140 Feature/care page skeleton
  src/pages/petCare/components/body-header/body-header.module.scss
  src/pages/petCare/components/care-body/care-body.component.tsx
  src/pages/petCare/components/care-body/care-body.module.scss
Labels: enhancement

#152 General clean-up
  .eslintrc.js
  src/App.css
  src/App.tsx
  src/pages/AddPet.tsx
  src/pages/Search.tsx
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/comparison.module.scss
  src/pages/filter/components/filter-header/filter-header.component.tsx
  src/pages/filter/components/slider/slider.component.tsx
  src/pages/filter/filter.scss
  src/pages/landing-page/landing-page.component.tsx
  src/pages/pet/components/additional-item/additional-item.module.scss
  src/pages/pet/components/characteristics/characteristics.module.scss
  src/pages/pet/components/observations/observations.module.scss
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.module.scss
  src/pages/petCare/components/additional-item/additonal-item.module.scss
  src/pages/petCare/components/care-body/care-body.component.tsx
  src/pages/petCare/components/header.component/logo.svg
  src/pages/petCare/components/header.component/logo2.svg
  src/pages/petCare/components/header.component/petCare-header.component.tsx
  src/pages/petCare/components/header.component/petCare-header.module.scss
  src/pages/petCare/pet-care.component.tsx
  src/pages/petCare/pet-care.module.scss
  src/pages/quiz-page/components/meal-input/meal-input.component.tsx
  src/pages/quiz-page/quiz-page.component.tsx
  src/pages/quiz-page/quiz-page.intarface.ts
  src/pages/quiz-page/quiz-page.module.scss
  src/pages/result/result.component.tsx
  src/pages/starter-pack/components/additional-info/additional-info.module.scss
  src/pages/starter-pack/components/from-breeder/from-breeder.module.scss
  src/pages/starter-pack/components/to-buy/to-buy.module.scss
  src/pages/starter-pack/starter-pack.component.tsx
  src/pages/starter-pack/starter-pack.module.scss
  src/shared/components/logo/logo.component.tsx
  src/shared/components/logo/logo.styles.css
  src/shared/constants/routes.constants.ts
  src/store/care/sagas/care.sagas 2.ts
  src/store/care/sagas/care.sagas.ts
  src/store/comparison/reducers/comparison-handler.reducer.ts
  src/store/comparison/reducers/comparison.reducer.ts
  src/store/comparison/services/get-pets-by-id-fetch.api.ts
  src/store/name-generator/sagas/name-generator.sagas.ts
  src/store/pet/sagas/pet.saga.ts
  src/store/quiz/actions/quiz.action.ts
  src/store/quiz/reducers/quiz.reducer.ts
  src/store/result/actions/result.actions.ts
  src/store/result/reducers/reducers.interfaces.ts
  src/store/result/reducers/result.reducer.ts
  src/store/result/sagas/result.saga.ts
Labels: enhancement

#154 Feature/error handling component
  src/images/error_dogs.png
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/comparison.interface.ts
  src/pages/pet/pet.component.tsx
  src/pages/pet/props.models.tsx
  src/pages/quiz-page/quiz-page.component.tsx
  src/pages/quiz-page/quiz-page.intarface.ts
  src/pages/result/result.component.tsx
  src/pages/result/result.interfaces.ts
  src/pages/starter-pack/starter-pack.component.tsx
  src/pages/starter-pack/starter-pack.interfaces.ts
  src/shared/components/error-handling/error-handling.component.tsx
  src/shared/components/error-handling/error-handling.module.scss
  src/store/comparison/reducers/comparison.reducer.ts
  src/store/pet/pet.models.ts
  src/store/pet/reducers/pet.reducer.ts
  src/store/result/reducers/reducers.interfaces.ts
  src/store/result/reducers/result.reducer.ts
  src/store/result/sagas/result.saga.ts
Labels: enhancement

#155 Feature/quiz care saving filter
  src/App.tsx
  src/pages/pet-care/components/additional-item/additional.interface.ts
  src/pages/pet-care/components/additional-item/additonal-item.component.tsx
  src/pages/pet-care/components/additional-item/additonal-item.module.scss
  src/pages/pet-care/components/additonal-section/additional-section.component.tsx
  src/pages/pet-care/components/additonal-section/additional-section.module.scss
  src/pages/pet-care/components/analysis-item/analysis-item.component.tsx
  src/pages/pet-care/components/analysis-item/analysis-item.interface.ts
  src/pages/pet-care/components/analysis-item/analysis-item.module.scss
  src/pages/pet-care/components/analysis-result/analysis-result.component.tsx
  src/pages/pet-care/components/analysis-result/analysis-result.module.scss
  src/pages/pet-care/components/analysis-result/result.interface.ts
  src/pages/pet-care/components/analysis-section/analysis-section.component.tsx
  src/pages/pet-care/components/analysis-section/analysis-section.module.scss
  src/pages/pet-care/components/body-header/body-header.component.tsx
  src/pages/pet-care/components/body-header/body-header.module.scss
  src/pages/pet-care/components/care-body/care-body.component.tsx
  src/pages/pet-care/components/care-body/care-body.module.scss
  src/pages/pet-care/components/care-body/careBody.interface.ts
  src/pages/pet-care/pet-care.component.tsx
  src/pages/pet-care/pet-care.module.scss
  src/pages/petCare/components/analysis-item/analysis-item.interface.ts
  src/pages/quiz-page/quiz-page.component.tsx
Labels: enhancement

#159 Pet page: Previously opened pet was shown few sec before the correct one
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.module.scss
  src/pages/starter-pack/components/additional-info/additional-info.component.tsx
  src/pages/starter-pack/starter-pack.component.tsx
  src/store/pet/actions/pet.actions.ts
  src/store/pet/reducers/pet.reducer.ts
Labels: bug

#158 Navigation menu
  src/App.module.scss
  src/App.tsx
  src/pages/comparison/comparison.component.tsx
  src/pages/filter/components/filter-header/filter-header.component.tsx
  src/pages/filter/components/filter-header/filter-header.module.scss
  src/pages/landing-page/landing-page.component.tsx
  src/pages/pet-care/pet-care.component.tsx
  src/pages/pet-care/pet-care.module.scss
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.module.scss
  src/pages/quiz-page/quiz-page.component.tsx
  src/pages/result/result.component.tsx
  src/pages/starter-pack/starter-pack.component.tsx
  src/pages/starter-pack/starter-pack.module.scss
  src/shared/components/header/components/menu/menu.component.tsx
  src/shared/components/header/components/menu/menu.interfaces.ts
  src/shared/components/header/components/menu/menu.module.scss
  src/shared/components/header/components/navigation/navigation.component.tsx
  src/shared/components/header/components/navigation/navigation.module.scss
  src/shared/components/header/header.component.tsx
  src/shared/components/header/header.module.scss
  src/shared/components/header/icons/burger-icon.svg
  src/shared/components/header/icons/cross-icon.svg
  src/shared/components/header/icons/home-icon.svg
  src/shared/components/header/icons/like-icon.svg
  src/shared/components/header/icons/paw-icon.svg
  src/shared/components/header/icons/question-icon.svg
  src/shared/components/header/icons/search-icon.svg
  src/shared/components/logo/logo.component.tsx
  src/shared/components/logo/logo.module.scss
  src/shared/components/logo/logo.styles.css
  src/shared/logo/logo.module.scss
Labels: enhancement

#160 Implement desktop version for comparison page
  src/pages/comparison/comparison.component.tsx
  src/pages/pet-care/pet-care.component.tsx
  src/pages/pet/pet.component.tsx
  src/pages/result/result.component.tsx
  src/pages/starter-pack/starter-pack.component.tsx
Labels: enhancement

#165 add error handling
  src/pages/pet-care/components/care-body/care-body.component.tsx
  src/store/care/reducers/care.reducers.ts
  src/store/care/sagas/care.sagas 2.ts
  src/store/care/sagas/care.sagas.ts
Labels: enhancement

#166 Add posibility to clear filter values from the result page
  src/pages/result/components/dog-search/dog-search.module.scss
  src/pages/result/components/filter-button/filter-button.component.tsx
  src/pages/result/components/filter-button/filter-button.module.scss
  src/pages/result/result.component.tsx
Labels: enhancement

#168 Implement desktop for landing page
  src/App.module.scss
  src/App.tsx
  src/index.css
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/comparison.module.scss
  src/pages/landing-page/components/find-out/find-out.module.scss
  src/pages/landing-page/components/to-pick-up/to-pick-up.module.scss
  src/pages/landing-page/landing-page.component.tsx
  src/pages/landing-page/landing-page.module.scss
  src/shared/components/footer/footer.component.tsx
  src/shared/components/footer/footer.module.scss
  src/shared/components/header/components/menu/menu.component.tsx
Labels: enhancement

#198 change slider logic, correct styles
  src/pages/filter/components/button/button.module.scss
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/pages/filter/components/filter-header/filter-header.module.scss
  src/pages/filter/components/input-radio/input-radio.module.scss
  src/pages/filter/components/overview-checkboxes/overview-checkboxes.module.scss
  src/pages/filter/components/slider/slider.component.tsx
  src/pages/filter/filter.scss
Labels: enhancement

#196 Feature/pet page desktop
  src/pages/pet/components/additional-item/additional-item.module.scss
  src/pages/pet/components/observations/observations.component.tsx
  src/pages/pet/components/observations/observations.module.scss
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.module.scss
Labels: enhancement

#195 Implement feature 'Scroll to top' after each redirecting
  src/App.tsx
  src/pages/comparison/comparison.component.tsx
  src/pages/comparison/components/profile/profile.component.tsx
  src/pages/comparison/utils/trim-breed.ts
  src/shared/components/footer/footer.module.scss
  src/shared/components/header/components/menu/menu.component.tsx
  src/shared/components/header/components/menu/menu.module.scss
  src/shared/components/header/components/navigation/navigation.component.tsx
  src/shared/components/header/components/navigation/navigation.module.scss
  src/shared/components/header/header.component.tsx
  src/shared/components/header/header.module.scss
  src/shared/components/header/icons/burger-icon.svg
  src/shared/components/header/icons/cross-icon.svg
  src/shared/components/header/icons/home-icon.svg
  src/shared/components/header/icons/like-icon.svg
  src/shared/components/header/icons/paw-icon.svg
  src/shared/components/header/icons/question-icon.svg
  src/shared/components/header/icons/search-icon.svg
  src/shared/components/loading-spinner/loading-spinner.module.scss
  src/shared/components/scroll-to-top/scroll-to-top.component.tsx
Labels: enhancement

#200 fix filter counter
  src/pages/filter/components/filter-body/filter-body.component.tsx
Labels: bug

#203 change api for breeds in quiz-page
  src/pages/quiz-page/quiz-page.component.tsx
  src/pages/quiz-page/quiz-page.intarface.ts
  src/store/quiz/actions/quiz.action.ts
  src/store/quiz/quiz.interface.ts
  src/store/quiz/reducers/quiz.reducer.ts
  src/store/quiz/sagas/quiz.sagas.ts
  src/store/root.reducer.ts
  src/store/root.saga.ts
Labels: enhancement

#201 Feature/name generator update
  src/pages/starter-pack/components/name-generator/name-generator.component.tsx
  src/pages/starter-pack/components/name-generator/name-generator.module.scss
  src/pages/starter-pack/starter-pack.module.scss
  src/store/name-generator/name-generator.models.ts
  src/store/name-generator/reducers/name-generator.reducers.ts
Labels: enhancement

#205 Imlement desktop version for header menu
  src/pages/landing-page/landing-page.module.scss
  src/shared/components/header/components/menu/menu.component.tsx
  src/shared/components/header/components/menu/menu.module.scss
  src/shared/components/header/components/navigation/navigation.component.tsx
  src/shared/components/header/components/navigation/navigation.module.scss
Labels: enhancement

#206 Desktop version of the result page
  src/pages/result/components/dog-images/dog-images.component.tsx
  src/pages/result/components/dog-images/dog-images.module.scss
  src/pages/result/components/dog/dog.module.scss
  src/pages/result/components/filter-button/filter-button.module.scss
  src/pages/result/result.component.tsx
  src/pages/result/result.module.scss
  src/shared/components/dog-characteristic/dog-characteristic.module.scss
  src/shared/components/header/components/navigation/navigation.component.tsx
Labels: enhancement

#208 Care-page, implement desktop styles and change skeleton
  src/pages/pet-care/components/additional-item/additonal-item.module.scss
  src/pages/pet-care/components/additonal-section/additional-section.module.scss
  src/pages/pet-care/components/analysis-item/analysis-item.module.scss
  src/pages/pet-care/components/analysis-result/analysis-result.module.scss
  src/pages/pet-care/components/analysis-section/analysis-section.module.scss
  src/pages/pet-care/components/body-header/body-header.module.scss
  src/pages/pet-care/components/care-body/care-body.module.scss
  src/pages/pet-care/pet-care.module.scss
Labels: enhancement

#209 Feature/header improvement
  src/shared/components/header/components/menu/menu.component.tsx
  src/shared/components/header/components/menu/menu.module.scss
  src/shared/components/header/components/navigation/navigation.component.tsx
Labels: enhancement

#210 Quize-page, add placeholder and validation
  src/pages/quiz-page/components/meal-input/meal-input.component.tsx
  src/pages/quiz-page/components/select-component/select.component.tsx
  src/pages/quiz-page/quiz-page.component.tsx
  src/pages/quiz-page/quiz-page.module.scss
Labels: enhancement

#214 Hide 'clear filter' button when no one filter value applied
  src/pages/result/components/filter-button/filter-button.component.tsx
  src/shared/components/header/components/menu/menu.component.tsx
Labels: enhancement

#216 Realese 1.5.0 to Develop
  package.json
Labels: enhancement

#235 Change font size quiz and filter page
  src/pages/filter/components/button/button.module.scss
  src/pages/filter/components/filter-body/filter-body.module.scss
  src/pages/filter/components/overview-checkboxes/overview-checkboxes.module.scss
  src/pages/filter/components/slider-section/slider-section.module.scss
  src/pages/filter/components/slider/slider.module.scss
  src/pages/filter/filter.scss
  src/pages/quiz-page/components/meal-input/meal-input.module.scss
  src/pages/quiz-page/components/radio-component/radio.module.scss
  src/pages/quiz-page/components/select-component/select.module.scss
  src/pages/quiz-page/quiz-page.component.tsx
  src/pages/quiz-page/quiz-page.module.scss
Labels: enhancement

#236 Remove padding-bottom on the result page in dog container
  src/pages/result/result.module.scss
Labels: enhancement

#241 Add Tooltip for Add pet to compare buttons
  package.json
  src/pages/comparison/components/profile/profile.component.tsx
  src/pages/comparison/components/remove-pet-button/remove-pet-button.module.scss
  src/pages/comparison/utils/trim-breed.ts
  src/pages/landing-page/components/find-out/find-out.component.tsx
  src/pages/landing-page/components/to-pick-up/to-pick-up.component.tsx
  src/pages/pet/pet.component.tsx
  src/pages/starter-pack/components/from-breeder/from-breeder.component.tsx
  src/pages/starter-pack/components/name-generator/name-generator.component.tsx
  src/pages/starter-pack/components/to-buy/to-buy.module.scss
  src/pages/starter-pack/starter-pack.component.tsx
  src/pages/starter-pack/starter-pack.interfaces.ts
  src/shared/components/add-pet-to-compare/add-pet-to-compare.component.tsx
  src/shared/components/add-pet-to-compare/add-pet-to-compare.module.scss
  src/shared/components/error-handling/error-handling.component.tsx
  src/shared/components/footer/footer.component.tsx
  src/shared/components/header/components/navigation/navigation.component.tsx
  src/shared/components/scroll-to-top/scroll-to-top.component.tsx
  src/store/name-generator/reducers/name-generator.reducers.ts
  src/store/pet/actions/pet.actions.ts
  src/store/pet/reducers/pet.reducer.ts
  src/store/result/reducers/result.reducer.ts
  yarn.lock
Labels: enhancement

#242 Pet Page, Starter Pack page: Fix image height&width for desktop
  src/pages/pet/pet.module.scss
  src/pages/starter-pack/starter-pack.module.scss
Labels: enhancement

#240 Bugfix/wrong menu closing
  src/App.module.scss
  src/App.scss
  src/App.tsx
  src/index.css
  src/pages/pet-care/components/analysis-section/analysis-section.module.scss
  src/pages/pet-care/pet-care.module.scss
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.module.scss
  src/pages/quiz-page/quiz-page.module.scss
  src/shared/components/content-wrapper/content-wrapper.interfaces.ts
  src/shared/components/content-wrapper/content-wrapper.module.scss
  src/shared/components/content-wrapper/content-wrapper.tsx
  src/shared/components/footer/footer.component.tsx
  src/shared/components/footer/footer.module.scss
  src/shared/components/header/components/menu/menu.module.scss
  src/shared/components/header/components/navigation/navigation.component.tsx
  src/shared/components/header/components/navigation/navigation.interfaces.ts
  src/shared/components/header/components/navigation/navigation.module.scss
  src/shared/components/header/header.component.tsx
  src/shared/components/header/header.module.scss
  src/store/menu/actions/menu.action.ts
  src/store/menu/reducers/menu.reducer.ts
  src/store/root.reducer.ts
Labels: bug

#244 add icons, change font size, implement open aadiction text fot desktop
  src/pages/pet-care/components/additional-item/additonal-item.component.tsx
  src/pages/pet-care/components/additional-item/additonal-item.module.scss
  src/pages/pet-care/components/additonal-section/additional-section.module.scss
  src/pages/pet-care/components/analysis-item/analysis-item.module.scss
  src/pages/pet-care/components/analysis-result/analysis-result.component.tsx
  src/pages/pet-care/components/analysis-result/analysis-result.module.scss
  src/pages/pet-care/components/body-header/body-header.module.scss
  src/pages/pet-care/components/care-body/care-body.module.scss
  src/pages/quiz-page/components/radio-component/radio.module.scss
  src/pages/quiz-page/quiz-page.component.tsx
  src/pages/quiz-page/quiz-page.module.scss
Labels: enhancement

#245 Reconcile names on the result page
  src/pages/filter/components/filter-body/filter-body.component.tsx
  src/pages/landing-page/components/find-out/find-out.module.scss
  src/pages/landing-page/components/to-pick-up/to-pick-up.module.scss
  src/pages/result/components/dog-search/dog-search.component.tsx
  src/shared/components/header/components/menu/menu.component.tsx
  src/shared/constants/routes.constants.ts
Labels: enhancement

#250 fix skeleton bug
  src/App.scss
  src/index.css
  src/pages/pet-care/components/additional-item/additonal-item.module.scss
  src/pages/pet-care/components/analysis-item/analysis-item.module.scss
  src/pages/pet-care/components/analysis-result/analysis-result.module.scss
  src/pages/pet-care/components/care-body/care-body.module.scss
  src/pages/pet-care/pet-care.module.scss
  src/store/care/reducers/care.reducers.ts
  src/store/filter/reducers/filter.reducer.ts
  src/store/quiz/reducers/quiz.reducer.ts
Labels: bug

#251 Pet page: implement skeleton while loading
  src/App.tsx
  src/pages/pet/components/skeleton/skeleton.component.tsx
  src/pages/pet/components/skeleton/skeleton.module.scss
  src/pages/pet/pet.component.tsx
  src/pages/pet/pet.models.ts
  src/pages/pet/pet.module.scss
  src/pages/quiz-page/components/meal-input/meal-input.component.tsx
  src/pages/starter-pack/starter-pack.component.tsx
  src/shared/components/content-wrapper/content-wrapper.interfaces.ts
  src/shared/components/content-wrapper/content-wrapper.tsx
  src/shared/components/dog-picture/dog-picture.component.tsx
  src/shared/components/dog-picture/dog-picture.interfaces.ts
  src/shared/components/footer/footer.component.tsx
  src/shared/components/header/components/navigation/navigation.component.tsx
  src/shared/components/header/components/navigation/navigation.interfaces.ts
  src/shared/components/header/header.component.tsx
  src/shared/models.ts
  src/store/menu/__tests__/menu.reducers.test.ts
  src/store/menu/actions/menu.action.ts
  src/store/menu/hardcoded-data.ts
  src/store/menu/reducers/menu.reducer.ts
  src/store/name-generator/__tests__/name-generator.reducers.test.ts
  src/store/name-generator/__tests__/name-generator.saga.test.ts
  src/store/name-generator/hardcoded-data.ts
  src/store/name-generator/sagas/name-generator.sagas.ts
  src/store/pet/__tests__/pet.reducers.test.ts
  src/store/pet/__tests__/pet.saga.test.ts
  src/store/pet/hardcoded-data.ts
  src/store/pet/sagas/pet.saga.ts
  src/store/root.reducer.ts
Labels: enhancement

#264 Implement unit tests for quiz reducers
  src/store/quiz/__tests__/quiz.reducer.test.ts
  src/store/quiz/mocks.ts
  src/store/quiz/reducers/quiz.reducer.ts
Labels: enhancement

#257 Unit tests for result page sagas and reducers
  src/shared/interfaces/pet-profile.interface.ts
  src/store/result/__tests__/result.reducers.test.ts
  src/store/result/__tests__/result.saga.test.ts
  src/store/result/mocks.ts
  src/store/result/reducers/result.reducer.ts
  src/store/result/sagas/result.saga.ts
Labels: enhancement

#258 Add hover effect on dog container in the result page
  src/pages/result/result.module.scss
Labels: enhancement

#266 Implement tests for comparison page (without saga)
  src/pages/comparison/comparison.interface.ts
  src/store/comparison/__tests__/comparison-handler.reducer.test.ts
  src/store/comparison/__tests__/comparison.reducer.test.ts
  src/store/comparison/__tests__/comparison.saga.test.ts
  src/store/comparison/actions/comparison.action.ts
  src/store/comparison/mocks.ts
  src/store/comparison/reducers/comparison-handler.reducer.ts
  src/store/comparison/reducers/comparison.reducer.ts
  src/store/comparison/sagas/comparison.saga.ts
Labels: enhancement

#263 Unit tests for filter and care page
  src/pages/pet-care/components/additonal-section/additional-section.module.scss
  src/store/care/__tests__/care.reducer.test.ts
  src/store/care/__tests__/care.saga.test.ts
  src/store/care/mocks.ts
  src/store/care/reducers/care.reducers.ts
  src/store/care/reducers/reducers.interfaces.ts
  src/store/care/sagas/care.sagas.ts
  src/store/filter/__tests__/filter.reducer.test.ts
  src/store/quiz/__tests__/quiz.sagas.test.ts
  src/store/quiz/actions/quiz.action.ts
  src/store/quiz/mocks.ts
  src/store/quiz/sagas/quiz.sagas.ts
Labels: enhancement

#265 Feature/header footer styles
  src/shared/components/footer/footer.component.tsx
  src/shared/components/footer/footer.module.scss
  src/shared/components/header/components/menu/menu.module.scss
  src/shared/components/header/header.module.scss
  src/shared/components/logo/logo.module.scss
Labels: enhancement

#269 remove kg from title
  src/pages/pet-care/components/analysis-item/analysis-item.component.tsx
Labels: bug

#271 Release 1.6.0 to Develop
  package.json
Labels: enhancement

#272 fix filter width bug
  src/pages/filter/filter.scss
Labels: bug

#273 Hotfix, fix filter width bug
  src/pages/filter/filter.scss
Labels: bug

#283 fix regex bug
  src/pages/pet-care/components/analysis-item/analysis-item.component.tsx
Labels: bug

#282 Remove regexp on comparison page
  src/pages/comparison/comparison.module.scss
  src/pages/comparison/components/comparison-display/comparison-display.module.scss
  src/pages/comparison/utils/trim-breed.ts
  src/pages/pet/components/additional-item/additional-item.component.tsx
  src/pages/pet/pet.component.tsx
  src/pages/starter-pack/components/additional-info/additional-info.component.tsx
  src/pages/starter-pack/starter-pack.component.tsx
  src/shared/components/header/components/navigation/navigation.module.scss
Labels: bug, enhancement

#286 Hotfix/fix regex
  src/pages/pet-care/components/analysis-item/analysis-item.component.tsx
Labels: bug

#288 Remove regexp on the result page
  src/pages/result/utils/getUrlValues.util.ts
  src/shared/components/header/components/menu/menu.component.tsx
Labels: bug

#289 Hotfix/landing page image
  src/pages/landing-page/components/find-out/find-out.component.tsx
  src/pages/landing-page/components/find-out/find-out.module.scss
  src/shared/components/footer/footer.component.tsx
  src/shared/components/header/components/menu/menu.component.tsx
Labels: bug

#287 Merging from master to develop
  src/pages/comparison/comparison.module.scss
  src/pages/comparison/components/comparison-display/comparison-display.module.scss
  src/pages/comparison/utils/trim-breed.ts
  src/pages/landing-page/components/find-out/find-out.component.tsx
  src/pages/landing-page/components/find-out/find-out.module.scss
  src/pages/pet/components/additional-item/additional-item.component.tsx
  src/pages/pet/pet.component.tsx
  src/pages/result/utils/getUrlValues.util.ts
  src/pages/starter-pack/components/additional-info/additional-info.component.tsx
  src/pages/starter-pack/starter-pack.component.tsx
  src/shared/components/footer/footer.component.tsx
  src/shared/components/header/components/menu/menu.component.tsx
  src/shared/components/header/components/navigation/navigation.module.scss
Labels: bug, enhancement

#294 Hotfix/test coverals
  package.json
  src/pages/filter/components/button/button.module.scss
  src/pages/filter/components/timePerMonth-checkboxes/timePerMonth-checkboxes.component.tsx
Labels: enhancement

#296 Hothix/size of tooltips
  src/pages/comparison/components/profile/profile.component.tsx
  src/shared/components/add-pet-to-compare/add-pet-to-compare.component.tsx
Labels: enhancement

#299 Fix landing img height
  src/pages/landing-page/components/find-out/find-out.module.scss
Labels: bug

#298 Master
  README.md
  package.json
  src/pages/comparison/components/profile/profile.component.tsx
  src/pages/filter/components/button/button.module.scss
  src/pages/filter/components/timePerMonth-checkboxes/timePerMonth-checkboxes.component.tsx
  src/pages/landing-page/components/find-out/find-out.module.scss
  src/pages/result/components/filter-button/filter-button.module.scss
  src/shared/components/add-pet-to-compare/add-pet-to-compare.component.tsx
Labels: enhancement

#301 Add the number of the filtred pets
  src/pages/result/components/dog/dog.component.tsx
  src/pages/result/result.component.tsx
  src/pages/result/result.module.scss
Labels: enhancement

#302 Release 1.7.1
  package.json
  src/pages/result/components/dog/dog.component.tsx
  src/pages/result/result.component.tsx
  src/pages/result/result.module.scss
Labels: enhancement

#303 Release 1.7.1 to develop
  package.json
Labels: enhancement
